# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
%define my_exec_dir "/usr/bin"
%if X%{_vendor} == "Xredhat"
%define qmake qmake-qt5 \
make
%else
%define qmake qmake \
make
%endif
%define qmake_install mkdir -p %{buildroot}%{my_exec_dir} && \
make INSTALL_ROOT=%{buildroot} install
%define my_buildhost non-meego-%{vendor}
# << macros

Name:       shownetif
Summary:    Show Ifconfig Utility
Version:    0.3.0
Release:    1
Group:      System/GUI/Other
License:    GPLv2
URL:        http://moui.sourceforge.net
Source0:    %{name}-%{version}.tar.gz
Requires:   geuzen-qml-utils
BuildRequires:  gcc-c++
BuildRequires:  desktop-file-utils
BuildRequires: qt5-qtbase-devel >= %{version}
BuildRequires: qt5-qtdeclarative-devel
BuildRequires: pkgconfig(Qt5Quick)


%description
Utility to show network configuration




%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post

mkdir -p %{buildroot}%{_datadir}/pixmaps
install -m 0644 images/%{name}.png %{buildroot}%{_datadir}/pixmaps
mkdir -p %{buildroot}%{_datadir}/applications
install -m 0644 %{name}.desktop %{buildroot}%{_datadir}/applications

# << install post
desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop






%files
%defattr(-,root,root,-)
/usr/bin/shownetif
/usr/share/applications/%{name}.desktop
/usr/share/pixmaps/%{name}.png
# >> files
# << files


